export enum PermissionType {

  AddCycle = "AddCycle",
  DeleteCycle = "DeleteCycle",
  UpdateCycle = "UpdateCycle",
  AddFaculty = "AddFaculty",
  DeleteFaculty = "DeleteFaculty",
  UpdateFaculty = "UpdateFaculty",
  AddLevel = "AddLevel",
  DeleteLevel = "DeleteLevel",
  UpdateLevel = "UpdateLevel",
  AddMatter = "AddMatter",
  DeleteMatter = "DeleteMatter",
  UpdateMatter = "UpdateMAtter",
  AddPost = "AddPost",
  DeletePost = "DeletePost",
  UpdatePost = "UpdatePost",
  AddMedia = "AddMedia",
  DeleteMedia = "DeleteMedia",
  UpdateMedia = "UpdateMedia",
  SeeHistory = "SeeHistory",
  SeeUsers = "SeeUsers",
  AddUser = "AddUser",
  SeeCycles = "SeeCycles",
  SeeMessages = "SeeMessages",
  Home = "Home",
  SendMessage = "SendMessage",
  SeeFaculties = "SeeFaculties",
  SeeLevels = "SeeLevels",
  SeeMatters = "SeeMatters",
  SeeMedias = "SeeMedias",
  SeePosts = "SeePosts",
  SeeContent = "SeeContent",
  DeleteMessage="DeleteMessage",
  DeleteUser = "DeleteUser"
}

